!
!**********************************************************************C
!**********************************************************************C
!**********************************************************************C
!
      SUBROUTINE TOXALL
!
! **  SUBROUTINE TOXALL WRITES ACCUMULATED TOXIC FLUXES
!
! **  THIS SUBROUTINE IS PART OF  EFDC-FULL VERSION 1.0a
!
! **  LAST MODIFIED BY JOHN HAMRICK ON 1 NOVEMBER 2001
!
!**********************************************************************C
!
!     VARIABLES WRITTEN TO TOXALL.OUT
!
!       ATOXPFWX  (L,NS,NT)= PARTICULATE ADVECTIVE X FLUX IN WATER COLUMN  NS=1,NSED+NSND+2
!       ATOXPFWY  (L,NS,NT)= PARTICULATE ADVECTIVE Y FLUX IN WATER COLUMN  NS=1,NSED+NSND+2
!       ATOXFDFWX (L,NT)   = FREE DISSOLVED ADVECTIVE X FLUX IN WATER COLUMN
!       ATOXFDFWY (L,NT)   = FREE DISSOLVED ADVECTIVE Y FLUX IN WATER COLUMN
!       ATOXCDFWX (L,NT)   = COMPLEXED DISSOLVED ADVECTIVE X FLUX IN WATER COLUMN
!       ATOXCDFWY (L,NT)   = COMPLEXED DISSOLVED ADVECTIVE Y FLUX IN WATER COLUMN
!       ATOXPFBLX (L,NS,NT)= BEDLOAD FLUX IN X DIRECTION, NS=1,NSND
!       ATOXPFBLY (L,NS,NT)= BEDLOAD FLUX IN Y DIRECTION, NS=1,NSND
!       ATOXSOUR  (L,NT)   = INFLOW FLUX TO WATER COLUMN
!       ATOXSINK  (L,NT)   = OUTFLOW FLUX FROM WATER COLUMN (WILL ALWAYS BE NEGATIVE)
!       ATOXVOL   (L,NT)   = VOLIIZATION FLUX FROM WATER COLUMN (WILL ALWAYS BE NEGATIVE)
!       ATOXPFBW  (L,NS,NT)= NET PARTICULATE FLUX FROM BED TO WATER COLUMN, NS=1,NSED+NSND+2
!       ATOXFDFBW (L,NT)   = NET FREE DISSOLVED FLUX FROM BED TO WATER COLUMN
!       ATOXCDFBW (L,NT)   = NET COMPLEXED DISSOLVED FLUX FROM BED TO WATER COLUMN
!       ATOXFBEBKB(L,NT)   = FLUX FORM BANK CELL DUE TO BANK EROSION
!       ATOXFBECHB(L,NT)   = FLUX TO CHANNEL BED DUE TO BANK EROSION
!       ATOXFBECHW(L,NT)   = FLUX TO CHANNEL WATER COLUMN DUE TO BANK EROSION
!
!     VARIABLES WRITTEN TO TOXALLB2W.OUT   (FLUXES BED TO WATER)
!
!       ATOXPFBWP (L,NS,NT)= POSITIVE ARTICULATE FLUX FROM BED TO WATER COLUMN, NS=1,NSED+NSND+2
!       ATOXFDFBWP(L,NT)   = POSITIVE FREE DISSOLVED FLUX FROM BED TO WATER COLUMN
!       ATOXCDFBWP(L,NT)   = POSITIVE COMPLEXED DISSOLVED FLUX FROM BED TO WATER COLUMN
!
!     VARIABLES WRITTEN TO OXALLW2B.OUT   (FLUXES WATER TO BED)
!
!       ATOXPFBWN (L,NS,NT)= NEGATIVE PARTICULATE FLUX FROM BED TO WATER COLUMN (IE WATER TO BED), NS=1,NSED+NSND+2
!       ATOXFDFBWN(L,NT)   = NEGATIVE FREE DISSOLVED FLUX FROM BED TO WATER COLUMN (IE WATER TO BED)
!       ATOXCDFBWN(L,NT)   = NEGATIVE COMPLEXED DISSOLVED FLUX FROM BED TO WATER COLUMN (IE WATER TO BED)
!
!     VARIBALES WRITTEN TO TOXALLBWAD.OUT  (PORE WATER ADVECTION AND DIFFUSION)
!
!       ATOXFDFBWAD(L,NT) = NET FREE DISSOLVED POREWATER FLUX FROM BED TO WATER COLUMN
!       ATOXCDFBWAD(L,NT) = NET COMPLEXED DISSOLVED POREWATER FLUX FROM BED TO WATER COLUMN
!
!     VARIBALES WRITTEN TO TOXALLB2WAD.OUT (PORE WATER ADVECTION AND DIFFUSION (FLUXES BED TO WATER)
!
!       ATOXFDFBWADP(L,NT)= POSITIVE FREE DISSOLVED POREWATER FLUX FROM BED TO WATER COLUMN
!       ATOXCDFBWADN(L,NT)= POSITIVE COMPLEXED DISSOLVED POREWATER FLUX FROM BED TO WATER COLUMN
!
!     VARIBALES WRITTEN TO TOXALLW2BAD.OUT (PORE WATER ADVECTION AND DIFFUSION (FLUXES WATER TO BED)
!
!       ATOXFDFBWADP(L,NT)= NEGATIVE FREE DISSOLVED POREWATER FLUX FROM BED TO WATER COLUMN (IE WATER TO BED)
!       ATOXCDFBWADP(L,NT)= NEGATIVE COMPLEXED DISSOLVED POREWATER FLUX FROM BED TO WATER COLUMN (IE WATER TO BED)
!
!**********************************************************************C
!
      INCLUDE 'EFDC.PAR'
      INCLUDE 'EFDC.CMN'
!
      CHARACTER*18 FNTMP(7)
!
!**********************************************************************C
!
       FNTMP(1)='TOXALL_PFWCADV.OUT'
       FNTMP(2)='TOXALL_FDWCADV.OUT'
       FNTMP(3)='TOXALL_PFBEDLD.OUT'
       FNTMP(4)='TOXALL_SORSINK.OUT'
       FNTMP(5)='TOXALL_PFBD2WC.OUT'
       FNTMP(6)='TOXALL_FDBD2WC.OUT'
       FNTMP(7)='TOXALL_BANKERO.OUT'
!
!**********************************************************************C
!
      IF(JSTOXALL.EQ.0)THEN
        OPEN(1,FILE='TOXALL.OUT')
        OPEN(2,FILE='TOXALLBW.OUT')
        OPEN(3,FILE='TOXALLB2W.OUT')
        OPEN(4,FILE='TOXALLW2B.OUT')
        OPEN(11,FILE='TOXALLBWAD.OUT')
        OPEN(12,FILE='TOXALLB2WAD.OUT')
        OPEN(13,FILE='TOXALLW2BAD.OUT')
        OPEN(14,FILE='SEDALL.OUT')
        CLOSE(1,STATUS='DELETE')
        CLOSE(2,STATUS='DELETE')
        CLOSE(3,STATUS='DELETE')
        CLOSE(4,STATUS='DELETE')
        CLOSE(11,STATUS='DELETE')
        CLOSE(12,STATUS='DELETE')
        CLOSE(13,STATUS='DELETE')
        CLOSE(14,STATUS='DELETE')
!
!   DEBUGGING FILES
!
!         DO IUNIT=21,27
!           IUNITF=IUNIT-20
!           OPEN(IUNIT,FILE=FNTMP(IUNITF))
!           CLOSE(IUNIT,STATUS='DELETE')
!         ENDDO
!
        JSTOXALL=1
      ENDIF
!
!**********************************************************************C
!
      OPEN(1,FILE='TOXALL.OUT',POSITION='APPEND')
      OPEN(2,FILE='TOXALLBW.OUT',POSITION='APPEND')
      OPEN(3,FILE='TOXALLB2W.OUT',POSITION='APPEND')
      OPEN(4,FILE='TOXALLW2B.OUT',POSITION='APPEND')
      OPEN(11,FILE='TOXALLBWAD.OUT',POSITION='APPEND')
      OPEN(12,FILE='TOXALLB2WAD.OUT',POSITION='APPEND')
      OPEN(13,FILE='TOXALLW2BAD.OUT',POSITION='APPEND')
      OPEN(14,FILE='SEDALL.OUT',POSITION='APPEND')
!
!  DEBUGGING FILES
!
!       DO IUNIT=21,27
!         IUNITF=IUNIT-20
!         OPEN(IUNIT,FILE=FNTMP(IUNITF),POSITION='APPEND')
!       ENDDO
!
      IF(ISDYNSTP.EQ.0)THEN
        TIME=(DT*FLOAT(N)+TCON*TBEGIN)/86400.
      ELSE
        TIME=TIMESEC/86400.
      ENDIF
!
      WRITE(1,100)TIME
      WRITE(2,100)TIME
      WRITE(3,100)TIME
      WRITE(4,100)TIME
      WRITE(11,100)TIME
      WRITE(12,100)TIME
      WRITE(13,100)TIME
      WRITE(14,100)TIME
!
!      DO IUNIT=21,27
!        WRITE(IUNIT,100)TIME
!      ENDDO
!
!      NTMP=NSED+NSND+2
      NTMP=NSED+NSND
!
      NT=1
      DO L=2,LA
        WRITE(1,101)IL(L),JL(L),
     &  (ATOXPFWX(L,NS,NT),NS=1,NTMP),(ATOXPFWY(L,NS,NT),NS=1,NTMP),
     &   ATOXFDFWX(L,NT),ATOXFDFWY(L,NT),ATOXCDFWX(L,NT),
     &   ATOXCDFWY(L,NT),
     &  (ATOXPFBLX(L,NS,NT),NS=1,NSND),(ATOXPFBLY(L,NS,NT),NS=1,NSND),
     &   ATOXSOUR(L,NT),ATOXSINK(L,NT),ATOXVOL(L,NT),
     &  (ATOXPFBW(L,NS,NT),NS=1,NTMP),ATOXFDFBW(L,NT),
     &  ATOXCDFBW(L,NT),ATOXFBEBKB(L,NT),
     &   ATOXFBECHB(L,NT),ATOXFBECHW(L,NT)
!
        WRITE(2,101)IL(L),JL(L),(ATOXPFBW(L,NS,NT),NS=1,NTMP),ATOXFDFBW(L,NT),ATOXCDFBW(L,NT)

        WRITE(3,101)IL(L),JL(L),(ATOXPFBWP(L,NS,NT),NS=1,NTMP),ATOXFDFBWP(L,NT),ATOXCDFBWP(L,NT)
!
        WRITE(4,101)IL(L),JL(L),(ATOXPFBWN(L,NS,NT),NS=1,NTMP),ATOXFDFBWN(L,NT),ATOXCDFBWN(L,NT)
!
        WRITE(11,101)IL(L),JL(L),ATOXFDFBWAD(L,NT),ATOXCDFBWAD(L,NT)
!
        WRITE(12,101)IL(L),JL(L),ATOXFDFBWADP(L,NT),ATOXCDFBWADP(L,NT)
!
        WRITE(13,101)IL(L),JL(L),ATOXFDFBWADN(L,NT),ATOXCDFBWADN(L,NT)
!
        WRITE(14,101)IL(L),JL(L),(ASEDFWX(L,NS),NS=1,NTMP),(ASEDFWY(L,NS),NS=1,NTMP),(ASEDFBLX(L,NS),NS=1,NSND),(ASEDFBLY(L,NS),NS=1,NSND)
!
!       'TOXALL_PFWCADV.OUT'
!
!        WRITE(21,101)IL(L),JL(L),
!     &  (ATOXPFWX(L,NS,NT),NS=1,NTMP),(ATOXPFWY(L,NS,NT),NS=1,NTMP)
!
!       'TOXALL_FDWCADV.OUT'
!
!        WRITE(22,101)IL(L),JL(L),ATOXFDFWX(L,NT),ATOXFDFWY(L,NT),
!     &   ATOXCDFWX(L,NT),ATOXCDFWY(L,NT)
!
!       'TOXALL_PFBEDLD.OUT'
!
!        WRITE(23,101)IL(L),JL(L),
!     &  (ATOXPFBLX(L,NS,NT),NS=1,NSND),(ATOXPFBLY(L,NS,NT),NS=1,NSND)
!
!       'TOXALL_SORSINK.OUT'
!
!         WRITE(24,101)IL(L),JL(L),ATOXSOUR(L,NT),ATOXSINK(L,NT),
!     &                           ATOXVOL(L,NT)
!
!       'TOXALL_PFBD2WC.OUT'
!
!        WRITE(25,101)IL(L),JL(L),(ATOXPFBW(L,NS,NT),NS=1,NTMP),
!     &    (ATOXPFBWP(L,NS,NT),NS=1,NTMP),(ATOXPFBWN(L,NS,NT),NS=1,NTMP)
!
!       'TOXALL_FDBD2WC.OUT'
!
!        WRITE(26,101)IL(L),JL(L),ATOXFDFBW(L,NT),ATOXFDFBWP(L,NT),ATOXFDFBWN(L,NT),
!     &      ATOXCDFBW(L,NT),ATOXCDFBWP(L,NT),ATOXCDFBWN(L,NT)
!
!       'TOXALL_BANKERO.OUT'
!
!         WRITE(27,101)IL(L),JL(L),ATOXFBEBKB(L,NT),
!     &   ATOXFBECHB(L,NT),ATOXFBECHW(L,NT)
!
      ENDDO
!
      CLOSE(1)
      CLOSE(2)
      CLOSE(3)
      CLOSE(4)
      CLOSE(11)
      CLOSE(12)
      CLOSE(13)
      CLOSE(14)
!
!  DEBUGGING FILES
!
!       DO IUNIT=21,27
!         CLOSE(IUNIT)
!       ENDDO
!
  100 FORMAT(F10.3)
  101 FORMAT(2I6,64E14.6)
!
!**********************************************************************C

      RETURN
      END