!
!**********************************************************************C
!**********************************************************************C
!**********************************************************************C
!
      SUBROUTINE WRSPLTH
!
! **  THIS SUBROUTINE IS PART OF  EFDC-FULL VERSION 1.0a 
!
! **  LAST MODIFIED BY JOHN HAMRICK ON 1 NOVEMBER 2001
!
!----------------------------------------------------------------------C
!
! CHANGE RECORD
! DATE MODIFIED     BY                 DATE APPROVED    BY
!
!----------------------------------------------------------------------C
!
! **  SUBROUTINE RSALPLTH WRITES FILES FOR RESIDUAL SCALAR FIELD 
! **  CONTOURING IN HORIZONTAL PLANES       
!
!**********************************************************************C
!
      INCLUDE 'EFDC.PAR'
      INCLUDE 'EFDC.CMN'
!
!**********************************************************************C
!
      REAL DBS(10)
      CHARACTER*80 TITLE
!
!**********************************************************************C
!
      IF(JSWRPH.NE.1) GOTO 300
!
!----------------------------------------------------------------------C
!
      LINES=LA-1
      LEVELS=2
      LEVELSS=3
      LEVEL1=1
      DBS(1)=0.
      DBS(2)=99.
      DBS(3)=-99.
!
        TITLE=' WAVE REYNOLDS STRESS RXX '
        LUN=21
        OPEN(LUN,FILE='WVRXXH.OUT',STATUS='UNKNOWN')
        CLOSE(LUN,STATUS='DELETE')
        OPEN(LUN,FILE='WVRXXH.OUT',STATUS='UNKNOWN')
        WRITE (LUN,99) TITLE
        WRITE (LUN,101)LINES,LEVELS
        WRITE (LUN,250)(DBS(L),L=1,LEVELS)
        CLOSE(LUN)
!
        TITLE=' WAVE REYNOLDS STRESS RYY '
        LUN=22
        OPEN(LUN,FILE='WVRYYH.OUT',STATUS='UNKNOWN')
        CLOSE(LUN,STATUS='DELETE')
        OPEN(LUN,FILE='WVRYYH.OUT',STATUS='UNKNOWN')
        WRITE (LUN,99) TITLE
        WRITE (LUN,101)LINES,LEVELS
        WRITE (LUN,250)(DBS(L),L=1,LEVELS)
        CLOSE(LUN)
!
        TITLE=' WAVE REYNOLDS STRESS RXY '
        LUN=23
        OPEN(LUN,FILE='WVRXYH.OUT',STATUS='UNKNOWN')
        CLOSE(LUN,STATUS='DELETE')
        OPEN(LUN,FILE='WVRXYH.OUT',STATUS='UNKNOWN')
        WRITE (LUN,99) TITLE
        WRITE (LUN,101)LINES,LEVELS
        WRITE (LUN,250)(DBS(L),L=1,LEVELS)
        CLOSE(LUN)
!
        TITLE=' WAVE DISSIPATION, (M/S)**3 '
        LUN=53
        OPEN(LUN,FILE='WVDISP.OUT',STATUS='UNKNOWN')
        CLOSE(LUN,STATUS='DELETE')
        OPEN(LUN,FILE='WVDISP',STATUS='UNKNOWN')
        WRITE (LUN,99) TITLE
        WRITE (LUN,101)LINES,LEVEL1
        WRITE (LUN,250)(DBS(L),L=1,LEVEL1)
        CLOSE(LUN)
!
        JSWRPH=0
!
!----------------------------------------------------------------------C
!
  300 CONTINUE
!
      OPEN(11,FILE='WVRXXH.COL',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(12,FILE='WVRYYH.COL',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(13,FILE='WVRXYH.COL',POSITION='APPEND',STATUS='UNKNOWN')
      CLOSE(11,STATUS='DELETE')
      CLOSE(12,STATUS='DELETE')
      CLOSE(13,STATUS='DELETE')
      OPEN(11,FILE='WVRXXH.COL',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(12,FILE='WVRYYH.COL',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(13,FILE='WVRXYH.COL',POSITION='APPEND',STATUS='UNKNOWN')
!
      OPEN(31,FILE='WVFXH.COL',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(32,FILE='WVFYH.COL',POSITION='APPEND',STATUS='UNKNOWN')
      CLOSE(31,STATUS='DELETE')
      CLOSE(32,STATUS='DELETE')
      OPEN(31,FILE='WVFXH.COL',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(32,FILE='WVFYH.COL',POSITION='APPEND',STATUS='UNKNOWN')
!
      OPEN(41,FILE='WVUBH.COL',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(42,FILE='WVVBH.COL',POSITION='APPEND',STATUS='UNKNOWN')
      CLOSE(41,STATUS='DELETE')
      CLOSE(42,STATUS='DELETE')
      OPEN(41,FILE='WVUBH.COL',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(42,FILE='WVVBH.COL',POSITION='APPEND',STATUS='UNKNOWN')
!
      OPEN(51,FILE='WVKX.COL',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(52,FILE='WVKY.COL',POSITION='APPEND',STATUS='UNKNOWN')
      CLOSE(51,STATUS='DELETE')
      CLOSE(52,STATUS='DELETE')
      OPEN(51,FILE='WVKX.COL',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(52,FILE='WVKY.COL',POSITION='APPEND',STATUS='UNKNOWN')
!
      OPEN(54,FILE='WVDISP.COL',POSITION='APPEND',STATUS='UNKNOWN')
      CLOSE(54,STATUS='DELETE')
      OPEN(54,FILE='WVDISP.COL',POSITION='APPEND',STATUS='UNKNOWN')
!
      OPEN(21,FILE='WVRXXH.OUT',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(22,FILE='WVRYYH.OUT',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(23,FILE='WVRXYH.OUT',POSITION='APPEND',STATUS='UNKNOWN')
      OPEN(53,FILE='WVDISP.OUT',STATUS='UNKNOWN')
!
      WRITE (21,100)N
      WRITE (22,100)N
      WRITE (23,100)N
!
      DO L=2,LA
      WVRSTOP=WVHUU(L,KC)+WVPP(L,KC)
      WVRSBOT=WVHUU(L,1)+WVPP(L,1)
      WRITE(11,200)IL(L),JL(L),WVRSTOP
      WRITE(21,200)IL(L),JL(L),DLON(L),DLAT(L),WVRSTOP,WVRSBOT
      WVRSTOP=WVHVV(L,KC)+WVPP(L,KC)
      WVRSBOT=WVHVV(L,1)+WVPP(L,1)
      WRITE(12,200)IL(L),JL(L),WVRSTOP
      WRITE(22,200)IL(L),JL(L),DLON(L),DLAT(L),WVRSTOP,WVRSBOT
      WRITE(13,200)IL(L),JL(L),WVHUV(L,KC)
      WRITE(23,200)IL(L),JL(L),DLON(L),DLAT(L),WVHUV(L,KC),WVHUV(L,1)
      WRITE(53,200)IL(L),JL(L),DLON(L),DLAT(L),WVDISP(L,KC)
      FXWTMP=0.5*(FXWAVE(L,KC)+FXWAVE(L+1   ,KC))
      FYWTMP=0.5*(FYWAVE(L,KC)+FYWAVE(LNC(L),KC))
      WRITE(31,200)IL(L),JL(L),FXWTMP
      WRITE(32,200)IL(L),JL(L),FYWTMP
!     FXWTMP=0.5*(WVUBU(L)+WVUBU(L+1   ))
!     FYWTMP=0.5*(WVVBV(L)+WVVBV(LSC(L)))
!     WRITE(41,200)IL(L),JL(L),FXWTMP
!     WRITE(42,200)IL(L),JL(L),FYWTMP
!     WRITE(51,200)IL(L),JL(L),WVACOS(L)
!     WRITE(52,200)IL(L),JL(L),WVASIN(L)
      WRITE(54,200)IL(L),JL(L),WVDISP(L,KC)
      ENDDO
!
      CLOSE(11)
      CLOSE(12)
      CLOSE(13)
      CLOSE(21)
      CLOSE(22)
      CLOSE(23)
      CLOSE(31)
      CLOSE(32)
      CLOSE(41)
      CLOSE(42)
      CLOSE(51)
      CLOSE(52)
      CLOSE(53)
      CLOSE(54)
!
!**********************************************************************C
!
   99 FORMAT(A80)
  100 FORMAT(I10)
  101 FORMAT(2I10)
  200 FORMAT(2I5,1X,6E14.6)
  250 FORMAT(12E12.4)
!MRM  200 FORMAT(2I5,1X,1P,6E13.5) 
!MRM  250 FORMAT(1P,12E11.3)
!
!**********************************************************************C
!
      RETURN
      END